; PlatformIO 项目配置 - 电动软弹枪火控 FCU
; 安装: pip install platformio
; 编译: pio run
; 上传: pio run -t upload
; 串口: pio device monitor -b 115200

[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.14.0
    miguelbalboa/MFRC522 @ ^1.4.12
